module.exports = {
  content: ['./src/**/*.{html,ts}'],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        'primary': '#9fb8ad',
        'primary-dark': '#475841',
        'bg-main': '#e6e8e6',
        'border-muted': '#ced0ce',
        'text-main': '#3f403f',
        'text-muted': '#6b6d6b',
        "tertiary": "#3a3d3c",
        "secondary-fixed": "#cfe8dc",
        "on-primary-fixed-variant": "#3b4b35",
        "on-error-container": "#93000a",
        "tertiary-container": "#515453",
        "surface-container-low": "#f2f4f2",
        "tertiary-fixed": "#e1e3e1",
        "surface-bright": "#f8faf8",
        "error-container": "#ffdad6",
        "background": "#f8faf8",
        "primary-fixed-dim": "#b9ccaf",
        "tertiary-fixed-dim": "#c5c7c5",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#cce6da",
        "on-surface": "#191c1b",
        "on-secondary-fixed-variant": "#354b43",
        "on-tertiary-fixed-variant": "#444746",
        "on-primary-fixed": "#101f0d",
        "outline": "#747870",
        "on-secondary-fixed": "#091f18",
        "on-secondary-container": "#50685e",
        "on-background": "#191c1b",
        "primary-fixed": "#d5e8ca",
        "surface-variant": "#e1e3e1",
        "on-primary": "#ffffff",
        "surface-dim": "#d8dad9",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#b9ccaf",
        "outline-variant": "#c4c8be",
        "secondary": "#4c635a",
        "surface-tint": "#52634b",
        "surface-container": "#eceeec",
        "primary-container": "#475841",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#b3ccc1",
        "surface-container-highest": "#e1e3e1",
        "on-tertiary-fixed": "#191c1b",
        "on-error": "#ffffff",
        "inverse-surface": "#2e3130",
        "on-tertiary-container": "#c6c8c6",
        "on-secondary": "#ffffff",
        "on-primary-container": "#bacdb0",
        "inverse-on-surface": "#eff1ef",
        "surface": "#f8faf8",
        "surface-container-high": "#e7e9e7",
        "on-surface-variant": "#444841"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xs": "4px",
        "unit": "4px",
        "sm": "8px",
        "lg": "24px",
        "gutter": "16px",
        "container-max": "1200px",
        "md": "16px",
        "xl": "40px"
      },
      fontFamily: {
        "label": ["Helvetica", "Arial", "sans-serif"],
        "h3": ["Helvetica", "Arial", "sans-serif"],
        "body-sm": ["Helvetica", "Arial", "sans-serif"],
        "h1": ["Helvetica", "Arial", "sans-serif"],
        "body-lg": ["Helvetica", "Arial", "sans-serif"],
        "body-md": ["Helvetica", "Arial", "sans-serif"],
        "h2": ["Helvetica", "Arial", "sans-serif"]
      },
      fontSize: {
        "label": ["12px", { "letterSpacing": "0.05em", "fontWeight": "600" }],
        "h3": ["18px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "body-sm": ["12px", { "lineHeight": "1.4", "fontWeight": "400" }],
        "h1": ["30px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "body-md": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "h2": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }]
      }
    }
  },
  plugins: [],
}